spring:
  profiles:
    active: local  # 기본은 로컬

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

mpc:
  api:
    url: http://localhost:8080/api/v1

blockchain:
  url: http://host.docker.internal:8545
  chain-id: 31337